name: Api CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'api/'
    branches: [ main ]
  pull_request:
    paths: 
      - 'api/'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: api
        
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install clean project
        working-directory: ./api     
        run: npm ci
        
      - name: Create project build
        working-directory: ./api     
        run: npm run build --if-present
      
      - name: Install eslint
        working-directory: ./api
        run: yarn add eslint
        
      - name: Run eslint
        working-directory: ./api     
        run: yarn run eslint
        
      - name: Run Tests
        working-directory: ./api     
        run: npm test
