name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths: 
      - 'frontend/'
    branches: [ main ]
  pull_request:
    paths: 
      - 'frontend/'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}        
      - name: Run commands
        run: | 
          npm ci
          npm run build --if-present
          yarn run eslint .
          npm test
